# Generated by Django 3.1.4 on 2021-02-01 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_no', models.CharField(max_length=100, unique=True)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Account_pin', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_opened', models.DateTimeField(default=datetime.date(2021, 2, 1), verbose_name='date')),
                ('balance_amount', models.IntegerField(default=500)),
            ],
        ),
    ]
