# Generated by Django 3.1.4 on 2021-02-02 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_opened',
            field=models.DateTimeField(default=datetime.date(2021, 2, 2), verbose_name='date'),
        ),
    ]
