# Generated by Django 3.1.4 on 2021-02-02 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210202_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.CharField(max_length=100, verbose_name='Enter account no')),
                ('amount', models.IntegerField()),
                ('date_of_transfer', models.DateTimeField(default=datetime.date(2021, 2, 2), verbose_name='date')),
                ('Account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
    ]
