# Generated by Django 3.1.4 on 2021-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='Account_no',
            field=models.CharField(max_length=100),
        ),
    ]
