# Generated by Django 3.1.6 on 2021-02-05 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210202_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Account_pin_1',
            field=models.IntegerField(default=0, verbose_name='Retype pin:'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Account_pin',
            field=models.IntegerField(verbose_name='Enter a pin (only digits):'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='date_opened',
            field=models.DateTimeField(default=datetime.date(2021, 2, 4), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_of_transfer',
            field=models.DateTimeField(default=datetime.date(2021, 2, 4), verbose_name='date'),
        ),
    ]
