# Generated by Django 3.1.6 on 2021-02-05 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210205_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_opened',
            field=models.DateField(default=datetime.date(2021, 2, 5), verbose_name='date'),
        ),
    ]
